### ISSUE TITLE
yarn start <exercise name> not working

### ISSUE THREAD

**Issue by simonccarter** [mike-works/typescript-fundamentals#142]
- [ ] **System Information**
  - [n/a] Browser type and version
  - [Sierra 10.13.6] OS type and version
  - [8.9.4] Node version
  - [3.1.6] TS version

- [ ] **Describe the bug**
Unable to run yarn start <exercise-name>.

- [ ] **To Reproduce**
1. clone repo
2. run `yarn global add typescript tslint ts-node`
2. run `yarn`
3. run `yarn start autocomplete-sfc`
4. see following error:

 Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/webpack/lib/Chunk.js:846:9)
    at /Users/scarter1/Dropbox/Development/tscriptFEM/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /Users/scarter1/Dropbox/Development/tscriptFEM/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/webpack/lib/Compilation.js:1242:27)
    at hooks.make.callAsync.err (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/webpack/lib/Compiler.js:546:17)
    at _err0 (eval at create (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _addModuleChain (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/webpack/lib/Compilation.js:1093:12)
    at processModuleDependencies.err (/Users/<name>/Dropbox/Development/tscriptFEM/node_modules/webpack/lib/Compilation.js:1005:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9
- [ ] **Expected behavior**
Able to run the code and see the output, for React.js excercises, in browser.

- [ ] **Screenshots (optional)**
![screen-shot-2018-11-21-at-09 01 36](https://user-images.githubusercontent.com/4021369/48827217-edff9100-ed6c-11e8-9698-a691d45c2b6c.jpg)

**Comment by mike-north** [comment]
thanks for this bug report. Master branch should contain a fix now c6c6f3e
