### ISSUE TITLE
No _first folder in the exercises folder

### ISSUE THREAD

**Issue by adyz** [mike-works/typescript-fundamentals#25]
I was watching this episode: [https://frontendmasters.com/courses/typescript/integrating-react-typescript](url) and tried to follow along, but I couldn't find this folder and `npm start _first` response is: 

```
Unknown exercise: _first! Valid exercises are:
        accounts
        autocomplete-2
        autocomplete-3
        autocomplete-4
        autocomplete-sfc
        cashier
        color-functions
        dealer
        fib
        stack
```

**Comment by zacaytion** [comment]
+1 
Here's the verbose log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/zah/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/Users/zah/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'start',
1 verbose cli   '_first' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mikeworks-typescript-workshop@0.0.1~prestart: mikeworks-typescript-workshop@0.0.1
6 info lifecycle mikeworks-typescript-workshop@0.0.1~start: mikeworks-typescript-workshop@0.0.1
7 verbose lifecycle mikeworks-typescript-workshop@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle mikeworks-typescript-workshop@0.0.1~start: PATH: /Users/zah/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zah/Projects/Education/typescript-fundamentals/node_modules/.bin:/Users/zah/.nvm/versions/node/v8.9.4/bin:/Users/zah/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mongodb:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/zah/.cargo/bin:/usr/local/bin/elixir:/usr/local/bin/erl:/opt/metasploit-framework/bin/:/Users/zah/.fzf/bin:/usr/local/bin/elixir:/usr/local/bin/erl:/opt/metasploit-framework/bin/
9 verbose lifecycle mikeworks-typescript-workshop@0.0.1~start: CWD: /Users/zah/Projects/Education/typescript-fundamentals
10 silly lifecycle mikeworks-typescript-workshop@0.0.1~start: Args: [ '-c', 'node server.js "_first"' ]
11 silly lifecycle mikeworks-typescript-workshop@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle mikeworks-typescript-workshop@0.0.1~start: Failed to exec start script
13 verbose stack Error: mikeworks-typescript-workshop@0.0.1 start: `node server.js "_first"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/zah/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/zah/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid mikeworks-typescript-workshop@0.0.1
15 verbose cwd /Users/zah/Projects/Education/typescript-fundamentals
16 verbose Darwin 17.4.0
17 verbose argv "/Users/zah/.nvm/versions/node/v8.9.4/bin/node" "/Users/zah/.nvm/versions/node/v8.9.4/bin/npm" "start" "_first"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error mikeworks-typescript-workshop@0.0.1 start: `node server.js "_first"`
22 error Exit status 1
23 error Failed at the mikeworks-typescript-workshop@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
I also tried hard coding the google API key in the `server.js` file and still received this error.

**Comment by mike-north** [comment]
#32 should fix this. Waiting for tests to pass

**Comment by zacaytion** [comment]
@mike-north that was fast 🚀 
🙌 thank you!

**Comment by mike-north** [comment]
Make sure to npm install again to get the appropriate downgrades to webpack and webpack-dev-server. `package-lock.json` has changed

**Comment by zacaytion** [comment]
Not getting any errors, but when I visit `localhost:3000` the page is completely blank.
Looked in the `_first/src` dir and there is only file `index.tsx` that is logging "hello world" to the console. 
In the FEM video you've got an `App.tsx` and `Clock.tsx` file there as well. 

I'm already familiar with React so I'm going to move on to the first autocomplete exercise. 
Just wanted to let you know. 

Thanks again the awesome videos and speedy response!

**Comment by mike-north** [comment]
there's not much interesting going on w/ the `_first` exercise. It's something I accidentally left in there and used as a demo at the last minute

**Comment by renschler** [comment]
@mike-north Is there anyway to overlay a note on the frontend masters video? I spent a little while trying to get _first running and then I realized there's not even an app.tsx file in the src folder anymore
