### ISSUE TITLE
when I try to run npm test accounts

### ISSUE THREAD

**Issue by sukumarkonduru** [mike-works/typescript-fundamentals#29]
I get this error.  I am running on windows and tried with git bash. I tried even npm install. Not sure if running yarn does the same thing. Appreciate any help.
----------------------------------------------------
Executing "C:\aaasukumar\typescript\tscript\scripts\test\index.sh":

> #!/bin/bash
> ./node_modules/.bin/jest --no-cache --watch $2

internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at module.exports (C:\aaasukumar\typescript\tscript\node_modules\scripty\lib                                                                                                                                  \run\spawn-script.js:8:15)
    at C:\aaasukumar\typescript\tscript\node_modules\scripty\lib\run\commandify.                                                                                                                                  js:6:7
    at C:\aaasukumar\typescript\tscript\node_modules\scripty\node_modules\async\                                                                                                                                  lib\async.js:718:13
    at iterate (C:\aaasukumar\typescript\tscript\node_modules\scripty\node_modul                                                                                                                                  es\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (C:\aaasukumar\typescript\tscrip                                                                                                                                  t\node_modules\scripty\node_modules\async\lib\async.js:281:9)
    at _parallel (C:\aaasukumar\typescript\tscript\node_modules\scripty\node_mod                                                                                                                                  ules\async\lib\async.js:717:9)
    at async.series (C:\aaasukumar\typescript\tscript\node_modules\scripty\node_                                                                                                                                  modules\async\lib\async.js:739:9)
npm ERR! Test failed.  See above for more details.

**Comment by mike-north** [comment]
Which windows version are you running?

**Comment by sukumarkonduru** [comment]
Mike, Thanks for the reply. I tried on Windows 7 Enterprise. I will try on my personal computer if it is problem with windows version.

**Comment by mike-north** [comment]
Windows 7 is outside of its mainstream support phase. I'm not sure what will and won't work.

I suggest trying with either
- Windows 10 with [Linux Subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10) installed
- A modern Linux variant like Ubuntu or Fedora
- OS X
